### ISSUE TITLE
Feature request: Alternative output formats

### ISSUE THREAD

**Issue by rpdelaney** [nedbat/dinghy#32] opened 2023-01-19 21:17 UTC
Could dinghy be configured to output in different formats than HTML? Like plain text, json, or markdown etc.

**Comment by rpdelaney** [comment] 2023-01-19 21:18
Related #31

**Comment by nedbat** [comment] 2023-01-19 23:25
I like this idea, and (other than the "public API" question from #31), might not be hard to implement.  As it is now, you can get some JSON data dumped out (for debugging):  set DINGHY_SAVE_RESULT=1 in your environment, and run dinghy.  You will have .json files, one for each of the .html files that is produced.  

Take a peek, and let me know if that would be a useful form to make real.

**Comment by nedbat** [comment] 2023-01-20 12:54
I've just made a change on main to prefix all of the dinghy keys in the data to make it easier to distinguish between the data direct from GraphQL and the data computed or rearranged by dinghy: f9feac9108d4ba4e81db0ab2c9e72310f8d7f170.

**Comment by rpdelaney** [comment] 2023-01-20 17:35
Nice! Yeah this is handy. Having a jinja template for markdown and plain text would still be handy though -- I'm working on alternative publishing solutions since we have a lot of private repos.

**Comment by nedbat** [comment] 2023-01-20 17:59
Just to be clear, I'm not recommending using this debugging output for real, it's just a way to talk about the internals.

I'm curious though: why do private repos require alternative publishing solutions? Dinghy just makes HTML files, it's up to you how to publish them.

**Comment by rpdelaney** [comment] 2023-01-20 19:49
I just don't want to engineer a separate access control solution.

**Comment by nedbat** [comment] 2023-01-20 19:59
I must be missing something about how you are using Dinghy.  All it does is write an HTML file. It has no say over who can see it, that depends entirely on where you put the file.

**Comment by nedbat** [comment] 2023-01-20 20:17
(from a separate conversation:) The issue is that HTML is not served well from GitHub repos. To piggy-back on the access controls of repos, a more readily rendered format like Markdown or ReStructured Text would be more useful.

**Comment by nedbat** [comment] 2023-01-21 02:43
In commit b4e750aa2bf0f1d436e7af8004a24bd94741f995, you can specify a ``template`` setting to choose your own Jinja2 template.  I haven't made a new release yet; let me know if you try it.

**Comment by nedbat** [comment] 2023-01-25 22:53
Custom templates is now released as part of [dinghy 1.1.0](https://pypi.org/project/dinghy/1.1.0).  Let me know if there's anything else needed.

**Closed by nedbat** 2023-01-25 22:53 UTC

**Comment by rpdelaney** [comment] 2023-01-25 23:52
Sweet! I haven't had a chance to try it yet, but I'll let you know if I have problems :) Thanks!
